//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prices
    {
        public int ID { get; set; }
        public int ID_Product { get; set; }
        public int Price { get; set; }
        public int PublishDate { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
